# Generated by Django 4.2.5 on 2023-10-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_list', to='tree_menu.menuitem', verbose_name='Объект MenuItem. Не обязателен если указан menu'),
        ),
    ]
